# Netlify configuration file

[build]
  command = "npm run build"
  publish = "dist"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3456
  targetPort = 3456
  publish = "dist"
  autoLaunch = true
  framework = "#custom" 